services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: boardgames
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  backend:
    build: ./backend
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend